name: Application2

on:
    push:
        branches:
            - 'main'
        paths-ignore:
            - 'Application1/**'
    pull_request:
        types:
            - opened
        branches:
            - 'main'
        paths-ignore:
            - 'Application1/**'
            - '.github/**'
        

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: shell_script_Application2
              run: |
                echo "Msg comes from Application2 Project"
