name: Application1

on:
    push:
        branches:
            - main
    pull_request:
        paths:
            - 'Application1/**'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: shell_script_Application1
              run: |
                echo "Msg comes from Application1 Project"