name: Application1

on:
    push:
        branches:
            - 'main'
            - 'feature/*'
#         paths:
#             - 'Application1/**'
    # pull_request:
    #     # types:
    #     #     - opened
    #     branches:
    #         - 'main'
    #         - 'feature/*'
        # paths:
        #     - 'Application1/**'
    workflow_dispatch:
        

jobs:
    # build:
    #     runs-on: windows-latest
    #     steps:
    #         - name: Checkout
    #           uses: actions/checkout@v3.5.3
    #         - name: shell_script_Application1
    #           run: |
    #             dir
    #             pwd.
    #           working-directory: Application4
    #         - name: Setup .NET Core SDK
    #           uses: actions/setup-dotnet@v3.2.0
    #           with:
    #             dotnet-version: 6.0.x
    #         - name: Install dependencies
    #           if: success() 
    #           # && github.ref == 'refs/heads/feature/sample' || github.ref == 'refs/heads/main'
    #           run: |
    #             dir
    #             # dotnet workload install maui
    #         - name: Setup .NET Core SDK
    #           if: failure()
    #           uses: actions/setup-dotnet@v3.2.0
    #           with:
    #             dotnet-version: 6.0.x
    #         - name: Install dependencies
    #           if: success() 
    #           # && github.ref == 'refs/heads/feature/sample' || github.ref == 'refs/heads/main'
    #           run: |
    #             dir
    #             # dotnet workload install maui

    # build1:
    #     needs: build
    #     runs-on: ubuntu-20.04
    #     if: success() && github.ref == 'refs/heads/feature/sample' || github.ref == 'refs/heads/main'
    #     steps:
    #         - name: shell_script_Application1
    #           run: |
    #             ls
    #             pwd
    job1:
      runs-on: ubuntu-latest
      # Map a step output to a job output
      outputs:
        output1: ${{ steps.step1.outputs.test }}
        output2: ${{ steps.step2.outputs.test }}
      steps:
        - id: step1
          run: echo "test=hello" >> "$GITHUB_OUTPUT"
        - id: step2
          run: echo "test=world" >> "$GITHUB_OUTPUT"
    job2:
      runs-on: ubuntu-latest
      needs: job1
      steps:
        - env:
            OUTPUT1: ${{needs.job1.outputs.output1}}
            OUTPUT2: ${{needs.job1.outputs.output2}}
          run: echo "$OUTPUT1 $OUTPUT2"