name: Application1

on:
    push:
        branches:
            - main
        paths:
            - 'Backend/**'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: shell_script_Backend
              run: |
                echo "Msg comes from Backend Project"