name: Application1

on:
    push:
        branches:
            - '*'
#         paths:
#             - 'Application1/**'
#     pull_request:
        # types:
        #     - opened
#         branches:
#             - 'main'
#         paths:
#             - 'Application1/**'
        

jobs:
    build:
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout
              uses: actions/checkout@v3.5.3
            - name: shell_script_Application1
              run: |
                ls
            - run: node --version
            - run: npm --version
