name: Application1

on:
    push:
        branches:
            - main
        paths:
            - 'Frontend/**'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: shell_script_Frontend
              run: |
                echo "Msg comes from Frontend Project"