name: Application1

on:
    push:
        branches:
            - '*'
        paths:
            - 'Application1/**'
    pull_request:
        # types:
        #     - opened
        branches:
            - 'main'
        paths:
            - 'Application1/**'
        

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: shell_script_Application1
              run: |
                echo "Msg comes from Application1 Project"