name: CI

on:
    pull_request:
        paths:
            - 'Backend/**'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1 
            - name: shell_script
              run: |
                echo "Msg comes from Backend Project"

