name: CI

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v1 
              
            - name: check_commit_msg
              id: check_commit
              run: |
                if [[ $(git log --no-merge --first-parent --name-only -- Backend/* | grep -Ev 'Backend/*') ]]; then
                    echo "name=match::true >> $GITHUB_OUTPUT"
                else
                    echo "name=match::false >> $GITHUB_OUTPUT"
                fi
            
            - name: shell_script
              if: ${{ steps.check_commit.outcome.match == 'true' }}
              run: |
                echo "Msg comes from Backend Project"

