name: CI

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v1 
              
            - name: check_commit_msg
              id: check_commit
              run: |
                if [[ $(git log --online --no-merges --first-parent --name-only -- Backend/ | grep -Ev 'Backend/') ]]; then
                    echo "::$GITHUB_OUTPUT name=match::true"
                else
                    echo "::$GITHUB_OUTPUT name=match::false"
                fi
            
            - name: shell_script
              if: ${{ steps.check_commit.outputs.match == 'true' }}
              run: |
                echo "Msg comes from Backend Project"

