name: CI

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v1 
              
            - name: check_commit_msg
              id: check_commit
              run: |
                if git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep -q '^Backend/'; then
                    echo "match=true" >> $GITHUB_OUTPUT
                    echo $GITHUB_OUTPUT
                else
                    echo "match=false" >> $GITHUB_OUTPUT
                fi
            
            - name: shell_script
              if: ${{ steps.check_commit.outputs.match == 'true' }}
              run: |
                echo "Msg comes from Backend Project"

