name: CI

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v1 
              
            - name: check_commit_msg
              id: check_commit
              run: |
                if [[ $(git log --first-parent --name-only -- Backend/ | grep -Ev 'Backend/') ]]; then
                    echo "::$GITHUB_OUTPUT name={name}::{value}"
                else
                    echo "::$GITHUB_OUTPUT name={name}::{value}"
                fi
            
            - name: shell_script
              if: ${{ steps.check_commit.outcome.match == 'true' }}
              run: |
                echo "Msg comes from Backend Project"

